version: "2"
linters:
  enable:
    - govet
    - staticcheck
    - unused
  exclusions:
    paths:
      - "./examples"
formatters:
  enable:
    - gofmt
    - goimports
    - golines
  exclusions:
    paths:
      - "./examples"