version: "2"
linters:
  settings:
    custom:
      tagcase:
        type: "module"
        settings:
          tags:
            snake:
              case: snake_case
            screamingSnake:
              case: SNAKE_CASE
            kebab:
              case: kebab-case
            screamingKebab:
              case: KEBAB-CASE
            pascal:
              case: PascalCase
            camel:
              case: camelCase
          initialism:
            enable:
              - BLAH
            disable:
              - ID
